substitutions:
  _SERVICE_NAME: budgeter

steps:
  # 1. Build image using Cloud Buildpacks
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds', 'submit',
      '--pack=image=gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--project=$PROJECT_ID',
      '.'
    ]

  # 2. Deploy to Cloud Run (global)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--allow-unauthenticated'
    ]

images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME

options:
  logging: CLOUD_LOGGING_ONLY