substitutions:
  _SERVICE_NAME: budgeter

steps:
  # Deploy to Cloud Run (global)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--allow-unauthenticated'
    ]

images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME

options:
  logging: CLOUD_LOGGING_ONLY