substitutions:
  _SERVICE_NAME: budgeter

steps:
  # Build image with Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args: [
      'pack', 'build', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--builder', 'gcr.io/buildpacks/builder',
      '--env', 'ENTRYPOINT=python run.py'
    ]

  # Delay to ensure the image is visible
  - name: 'bash'
    entrypoint: 'bash'
    args: ['-c', 'sleep 10']

  # Deploy to Cloud Run (global)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--allow-unauthenticated'
    ]

images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME

options:
  logging: CLOUD_LOGGING_ONLY