steps:
  # 1. Use Cloud Native Buildpacks to build image from Python app
  - name: 'gcr.io/buildpacks/builder'
    entrypoint: pack
    args:
      [
        'build',
        'gcr.io/concepter/budgeter',
        '--builder',
        'gcr.io/buildpacks/builder',
        '--env',
        'GOOGLE_ENTRYPOINT=python run.py'
      ]

  # 2. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'budgeter',
        '--image', 'gcr.io/concepter/budgeter',
        '--region', 'europe-west2',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
